version: '3.8'

services:
  solr:
    ports:
      - "8983:8983"
  fcrepo:
    ports:
      - "8080:8080"
  db:
    ports:
      - "5432:5432"
  web:
    environment:
      - HYKU_ADMIN_HOST=lvh.me
      - HYKU_DEFAULT_HOST=%{tenant}.lvh.me
      - HYKU_ROOT_HOST=lvh.me
    ports:
      - "3000:3000"
