---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hyku.rails-env.name" . }}
data:
  DATABASE_HOST: {{ template "hyku.postgres.name" . }}
  FEDORA_URL: http://{{ template "hyku.fcrepo.name" . }}:8080/fcrepo/rest
  RAILS_CACHE_STORE_URL: redis://{{ template "hyku.redis.name" . }}:6379/1 
  REDIS_HOST: {{ template "hyku.redis.name" . }}
  REDIS_URL: redis://{{ template "hyku.redis.name" . }}:6379/1
  SIDEKIQ_TIMEOUT: {{ .Values.sidekiq.timeout | quote }}
  SOLR_URL: http://{{ template "hyku.solr.name" . }}:8983/solr/hyku
  SETTINGS__SOLR_URL: http://{{ template "hyku.solr.name" . }}:8983/solr/
  SETTINGS__ZOOKEEPER__CONNECTION_STR: {{ template "hyku.zookeeper.name" . }}:2181/configs

{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
