---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "hyku.setup.name" . }}
  labels:
    app: {{ template "hyku.name" . }}
    chart: {{ template "hyku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: {{ template "hyku.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      {{- if .Values.rails.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.rails.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "hyku.rails-env.name" . }}-shared
      containers:
        - name: setup
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          volumeMounts:
            - mountPath: /home/app/webapp/public/assets
              name: shared
              subPath: assets
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "(bundle check || bundle install) && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rake assets:precompile && bundle exec rails zookeeper:upload"
          envFrom:
            - configMapRef:
                name: {{ template "hyku.rails-env.name" . }}
            - secretRef:
                name: {{ template "hyku.rails-env.name" . }}
