terms:
  - id: Community college / Lower division
    term: Community college / Lower division
  - id: College / Upper division
    term: College / Upper division
  - id: Graduate / Professional
    term: Graduate / Professional
  - id: Career / Technical
    term: Career / Technical
  - id: Adult education
    term: Adult education