# Hi - please dont edit this file directly, instead make changes in your .env file

login: &login
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] || 'hyku' %>
  pool: 5
  timeout: 5000


development:
  <<: *login

test:
  <<: *login
  database: <%= ENV['TEST_DB'] || 'hyku_test' %>

staging:
  <<: *login


production:
  <<: *login
