# Hi - please dont edit this file directly, instead make changes in your .env file

login: &login
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] || 'hyku' %>
  pool: 50
  timeout: 5000


development:
  <<: *login

test:
  <<: *login
  database: <%= ENV['DATABASE_TEST_NAME'] || 'hyku_test' %>

staging:
  <<: *login


production:
  <<: *login
