development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
test:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
production:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  sentinel:
    host: <%= ENV['REDIS_SENTINEL_HOST'] %>
    port: <%= ENV['REDIS_SENTINEL_PORT'] || 26379 %>