schema_org:
  accessibility_feature_type:
    Alternative Text: "http://schema.org/accessibilityFeature"
    Audio Description: "http://schema.org/accessibilityFeature"
    Braille: "http://schema.org/accessibilityFeature"
    Captions: "http://schema.org/accessibilityFeature"
    ChemML: "http://schema.org/accessibilityFeature"
    Described Math: "http://schema.org/accessibilityFeature"
    Display Transformability: "http://schema.org/accessibilityFeature"
    Haptic: "http://schema.org/accessibilityFeature"
    High Contrast: "http://schema.org/accessibilityFeature"
    Large Print: "http://schema.org/accessibilityFeature"
    Latex: "http://schema.org/accessibilityFeature"
    Long Description: "http://schema.org/accessibilityFeature"
    MathML: "http://schema.org/accessibilityFeature"
    Nemeth Braille: "http://schema.org/accessibilityFeature"
    Sign Language: "http://schema.org/accessibilityFeature"
    Structural Navigation: "http://schema.org/accessibilityFeature"
    Tactile Graphics: "http://schema.org/accessibilityFeature"
    Transcript: "http://schema.org/accessibilityFeature"
  accessibility_hazard_type:
    Flashing: "http://schema.org/accessibilityHazard"
    Motion: "http://schema.org/accessibilityHazard"
    Simulation: "http://schema.org/accessibilityHazard"
    Sound: "http://schema.org/accessibilityHazard"
  based_near:
    property: contentLocation
    type: "http://schema.org/Place"
    value: name
  contributor:
    property: contributor
    # used as the itemprop value for itemscoped attributes
    type: "http://schema.org/Person"
    value: name
  creator:
    property: creator
    type: "http://schema.org/Person"
    value: name
  date_created:
    property: dateCreated
  description:
    property: description
  keyword:
    property: keywords
  language:
    property: inLanguage
  publisher:
    property: publisher
    type: "http://schema.org/Organization"
    value: name
  resource_type:
    Article: "http://schema.org/Article"
    Audio: "http://schema.org/AudioObject"
    Book: "http://schema.org/Book"
    Conference Proceeding: "http://schema.org/ScholarlyArticle"
    Dataset: "http://schema.org/Dataset"
    Dissertation: "http://schema.org/ScholarlyArticle"
    Image: "http://schema.org/ImageObject"
    Map or Cartographic Material: "http://schema.org/Map"
    Masters Thesis: "http://schema.org/ScholarlyArticle"
    Part of Book: "http://schema.org/Book"
    Research Paper: "http://schema.org/ScholarlyArticle"
    Software or Program Code: "http://schema.org/Code"
    Video: "http://schema.org/VideoObject"
  subject:
    property: about
    type: "http://schema.org/Thing"
    value: name
  title:
    property: name
