default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  image_uploadtab: true
  toolbar1: styleselect | bold italic underline | link hr | undo redo
  toolbar2: indent outdent | alignleft aligncenter alignright | table | fullscreen 
  plugins:
    - table
    - fullscreen
    - link
    - autolink
custom:
  <<: *default
