---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hyku.fcrepo-env.name" . }}
data:
  DATABASE_PASSWORD: {{ .Values.env.secret.DATABASE_PASSWORD | b64enc }}
  JAVA_OPTS: {{ printf "-Dfcrepo.modeshape.configuration=\"classpath:/config/jdbc-postgresql-s3/repository.json\" -Dfcrepo.postgresql.host=\"%s\" -Dfcrepo.postgresql.username=\"%s\" -Dfcrepo.postgresql.password=\"%s\" -Daws.accesskeyid=\"akiajtotwt5elvqz6ifq\" -Daws.secretkey=\"p/318tmjvyjrpeaq5t9mocb83vizjgfjm2emhxv8\" -Daws.bucket=\"palni-staging\"" ( include "hyku.postgres.name" . ) .Values.env.configmap.DATABASE_USER .Values.env.secret.DATABASE_PASSWORD | b64enc }}

