---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hyku.fcrepo-env.name" . }}
data:
  POSTGRES_PASSWORD: {{ .Values.env.secret.POSTGRES_PASSWORD | b64enc }}
  JAVA_OPTS: {{ .Values.env.secret.FCREPO_OPTS | b64enc }}
