---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hyku.postgres.name" . }}
  labels:
    app: {{ template "hyku.name" . }}
    chart: {{ template "hyku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: {{ template "hyku.name" . }}
    release: {{ .Release.Name }}
    component: postgres
