---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hyku.postgres.name" . }}
  labels:
    app: {{ template "hyku.name" . }}
    chart: {{ template "hyku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  storageClassName: {{ .Values.postgres.storage.className }}
