---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hyku.rails-env.name" . }}
data:
  SECRET_KEY_BASE: {{ .Values.env.secret.SECRET_KEY_BASE | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.secret.POSTGRES_PASSWORD | b64enc }}
