# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  
  property :collection_subtitle, predicate: ::RDF::URI('https://hykucommons.org/terms/collection_subtitle') do |index|
    index.as :stored_searchable, :facetable
  end
  
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = CollectionIndexer
end
