apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-rttnv
    field.cattle.io/ingressState: '{"cGFscy9wYWxzaHlrdS8vLy8zMDAw":""}'
    field.cattle.io/publicEndpoints: "null"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"field.cattle.io/creatorId":"user-rttnv","field.cattle.io/ingressState":"{\"cGFscy9wYWxzaHlrdS8vLy8zMDAw\":\"\"}","field.cattle.io/publicEndpoints":"null"},"creationTimestamp":null,"generation":1,"name":"pals","namespace":"palshyku","selfLink":"/apis/extensions/v1beta1/namespaces/palshyku/ingresses/pals"},"spec":{"backend":{"serviceName":"web","servicePort":3000}},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  generation: 1
  name: pals
  selfLink: /apis/extensions/v1beta1/namespaces/palshyku/ingresses/pals
spec:
  backend:
    serviceName: web
    servicePort: 3000
status:
  loadBalancer: {}
