name: "Build Lint Test"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - i492-hyku-upgrade # TODO: remove

jobs: 
  call-workflow:
    uses: scientist-softserv/build-lint-test-action/.github/workflows/build-test-lint.yaml@v0.0.1
