name: "Build Lint Test"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - i492-hyku-upgrade # TODO: remove
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@self-hosted-runner
    with:
      target: hyku-base
      worker: true
      workerTarget: hyku-worker
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@v0.0.1
    with:
      worker: true
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@v0.0.1
    with:
      worker: true
  retag:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/retag.yaml@v0.0.1
    with:
      worker: true
