name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_step:
        required: false
        description: 'Pause the selected step to debug using tmate'
        type: choice
        default: ''
        options:
          - ''
          - build
          - test
          - lint

jobs:
  build:
    uses: scientist-softserv/actions/.github/workflows/build.yaml@choose-which-step-to-debug-with-tmate
    secrets: inherit
    with:
      platforms: "linux/amd64"
      webTarget: hyku-base
      solrTarget: hyku-solr
      workerTarget: hyku-worker
  test:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/test.yaml@choose-which-step-to-debug-with-tmate
  lint:
    needs: build
    uses: scientist-softserv/actions/.github/workflows/lint.yaml@choose-which-step-to-debug-with-tmate
    with:
      rubocop_cmd: 'bundle exec rubocop --parallel --format progress'

