name: "Deploy"
run-name: Deploy to Prod (${{ github.HEAD_TAG::8 }} -> ${{ inputs.environment }}) by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to Environment'
        require: true
        default: 'staging'
        type: choice
        options:
          - demo
          - production
          - staging
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  deploy:
    uses: scientist-softserv/actions/.github/workflows/deploy.yaml@v0.0.6
    secrets: inherit
